/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Andres
 */
public class OpenCountryData extends javax.swing.JFrame {

    /**
     * Creates new form Abrir
     */
    private File FILE, FileMap, FileShortName, FileFullName, FileTechName, FileFuelName;
    private File[] FileList;
    private boolean AllOK = false;
    private final int Nodes, Tech, TS, Years, Fuel;

    private final String[] GRName = {
        "Dem",
        "Cap",
        "NewCap",
        "Gen",
        "InvCos",
        "ManCos",
        "OpeCos",
        "PolCos",
        "GHGEmi",
        "WatCon",
        "WatWit",
        "InvCapEmp",
        "ManCapEmp",
        "OpeCapEmp",
        "FueCapEmp",
        "RetCapEmp",
        "EneMarPri",
        "ExiCap",
        "FueCos"};

    private ArrayList<String> GR_NAME;
    private ArrayList<String> TECH_NAME;

    public OpenCountryData(int Nodes, int Tech, int TS, int Years, int Fuel) {
        initComponents();
        setLocationRelativeTo(null);
        this.Nodes = Nodes;
        this.Tech = Tech;
        this.TS = TS;
        this.Years = Years;
        this.Fuel = Fuel;
        INI();
    }

    private void INI() {

        GR_NAME = new ArrayList<>();
        TECH_NAME = new ArrayList<>();

        for (String GN : GRName) {
            GR_NAME.add(GN);
        }
        int ALL_TS = this.TS * this.Years;
        jTextArea1.setText("Nodes size:\t" + Nodes + "\n");
        jLabel_Formato_ExiCap.setText(Nodes + " x " + Tech);
        jLabel_Formato_FueCos.setText(String.valueOf(ALL_TS));
        jLabel_Formato_Cap.setText(Nodes + " x " + ALL_TS);
        jLabel_Formato_Dem.setText(Nodes + " x " + ALL_TS);
        jLabel_Formato_EneMarPri.setText(Nodes + " x " + ALL_TS);
        jLabel_Formato_FueCapEmp.setText(Nodes + " x " + ALL_TS);
        jLabel_Formato_GHGEmi.setText(Nodes + " x " + ALL_TS);
        jLabel_Formato_Gen.setText(Nodes + " x " + ALL_TS);
        jLabel_Formato_InvCapEmp.setText(Nodes + " x " + ALL_TS);
        jLabel_Formato_InvCos.setText(Nodes + " x " + ALL_TS);
        jLabel_Formato_ManCapEmp.setText(Nodes + " x " + ALL_TS);
        jLabel_Formato_ManCos.setText(Nodes + " x " + ALL_TS);
        jLabel_Formato_NewCap.setText(Nodes + " x " + ALL_TS);
        jLabel_Formato_OpeCapEmp.setText(Nodes + " x " + ALL_TS);
        jLabel_Formato_OpeCos.setText(Nodes + " x " + ALL_TS);
        jLabel_Formato_PolCos.setText(Nodes + " x " + ALL_TS);
        jLabel_Formato_RetCapEmp.setText(Nodes + " x " + ALL_TS);
        jLabel_Formato_WatCon.setText(Nodes + " x " + ALL_TS);
        jLabel_Formato_WatWit.setText(Nodes + " x " + ALL_TS);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jTextField_FilePath_MAP = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel_CHECK_MAP = new javax.swing.JLabel();
        jLabel_CHECK_ShortName = new javax.swing.JLabel();
        jLabel_CHECK_FullName = new javax.swing.JLabel();
        jLabel_Name_MAP = new javax.swing.JLabel();
        jLabel_Name_ShortName = new javax.swing.JLabel();
        jLabel_Name_FullName = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel_CHECK_Tech = new javax.swing.JLabel();
        jLabel_Name_Tech = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel_CHECK_Fuel = new javax.swing.JLabel();
        jLabel_Name_Fuel = new javax.swing.JLabel();
        jButton_HelpMap = new javax.swing.JButton();
        jButton_HelpShortName = new javax.swing.JButton();
        jButton_HelpFullName = new javax.swing.JButton();
        jButton_HelpTechName = new javax.swing.JButton();
        jButton_FuelName = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel_Formato_Dem = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel_Formato_ExiCap = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel_Formato_Cap = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel_Formato_NewCap = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel_Formato_Gen = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel_Formato_InvCos = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel_Formato_ManCos = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel_Formato_OpeCos = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel_Formato_FueCos = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel_Formato_PolCos = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel_Formato_GHGEmi = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel_Formato_WatCon = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel_Formato_WatWit = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel_Formato_InvCapEmp = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel_Formato_ManCapEmp = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel_Formato_OpeCapEmp = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel_Formato_FueCapEmp = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel_Formato_RetCapEmp = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel_Formato_EneMarPri = new javax.swing.JLabel();
        jButton_Continue = new javax.swing.JButton();
        jButton_ShowMap = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Select File");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField_FilePath_MAP.setText("FilePath");

        jLabel1.setText("Upload country data");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("DT"));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel3.setText("MAP");
        jPanel2.add(jLabel3, new java.awt.GridBagConstraints());

        jLabel4.setText("Short Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel2.add(jLabel4, gridBagConstraints);

        jLabel5.setText("Full Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel2.add(jLabel5, gridBagConstraints);

        jLabel_CHECK_MAP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/NULL.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 18, 0, 10);
        jPanel2.add(jLabel_CHECK_MAP, gridBagConstraints);

        jLabel_CHECK_ShortName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/NULL.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 18, 0, 10);
        jPanel2.add(jLabel_CHECK_ShortName, gridBagConstraints);

        jLabel_CHECK_FullName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/NULL.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 18, 0, 10);
        jPanel2.add(jLabel_CHECK_FullName, gridBagConstraints);

        jLabel_Name_MAP.setText("null");
        jPanel2.add(jLabel_Name_MAP, new java.awt.GridBagConstraints());

        jLabel_Name_ShortName.setText("null");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        jPanel2.add(jLabel_Name_ShortName, gridBagConstraints);

        jLabel_Name_FullName.setText("null");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        jPanel2.add(jLabel_Name_FullName, gridBagConstraints);

        jLabel17.setText("Tech Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        jPanel2.add(jLabel17, gridBagConstraints);

        jLabel_CHECK_Tech.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/NULL.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 18, 0, 10);
        jPanel2.add(jLabel_CHECK_Tech, gridBagConstraints);

        jLabel_Name_Tech.setText("null");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        jPanel2.add(jLabel_Name_Tech, gridBagConstraints);

        jLabel8.setText("Fuel Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel2.add(jLabel8, gridBagConstraints);

        jLabel_CHECK_Fuel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/NULL.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 18, 0, 10);
        jPanel2.add(jLabel_CHECK_Fuel, gridBagConstraints);

        jLabel_Name_Fuel.setText("null");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        jPanel2.add(jLabel_Name_Fuel, gridBagConstraints);

        jButton_HelpMap.setText("help");
        jButton_HelpMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_HelpMapActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel2.add(jButton_HelpMap, gridBagConstraints);

        jButton_HelpShortName.setText("help");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel2.add(jButton_HelpShortName, gridBagConstraints);

        jButton_HelpFullName.setText("help");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel2.add(jButton_HelpFullName, gridBagConstraints);

        jButton_HelpTechName.setText("help");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel2.add(jButton_HelpTechName, gridBagConstraints);

        jButton_FuelName.setText("help");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel2.add(jButton_FuelName, gridBagConstraints);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("DT"));
        jPanel3.setLayout(new java.awt.GridLayout(0, 3, 8, 0));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Dem");
        jPanel3.add(jLabel6);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Demand");
        jPanel3.add(jLabel7);

        jLabel_Formato_Dem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Formato_Dem.setText("N x TS");
        jPanel3.add(jLabel_Formato_Dem);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("ExiCap");
        jPanel3.add(jLabel9);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Initial Generation Capacity");
        jPanel3.add(jLabel10);

        jLabel_Formato_ExiCap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Formato_ExiCap.setText("N x T");
        jPanel3.add(jLabel_Formato_ExiCap);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Cap");
        jPanel3.add(jLabel12);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Accumulated Capacity");
        jPanel3.add(jLabel13);

        jLabel_Formato_Cap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Formato_Cap.setText("N x TS");
        jPanel3.add(jLabel_Formato_Cap);

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("NewCap");
        jPanel3.add(jLabel15);

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("New Capacity");
        jPanel3.add(jLabel16);

        jLabel_Formato_NewCap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Formato_NewCap.setText("N x TS");
        jPanel3.add(jLabel_Formato_NewCap);

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Gen");
        jPanel3.add(jLabel18);

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Generation");
        jPanel3.add(jLabel19);

        jLabel_Formato_Gen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Formato_Gen.setText("N x TS");
        jPanel3.add(jLabel_Formato_Gen);

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("InvCos");
        jPanel3.add(jLabel21);

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Investment Cost");
        jPanel3.add(jLabel22);

        jLabel_Formato_InvCos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Formato_InvCos.setText("N x TS");
        jPanel3.add(jLabel_Formato_InvCos);

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("ManCos");
        jPanel3.add(jLabel24);

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Maintenance Cost");
        jPanel3.add(jLabel25);

        jLabel_Formato_ManCos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Formato_ManCos.setText("N x TS");
        jPanel3.add(jLabel_Formato_ManCos);

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("OpeCos");
        jPanel3.add(jLabel27);

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Operation Cost");
        jPanel3.add(jLabel28);

        jLabel_Formato_OpeCos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Formato_OpeCos.setText("N x TS");
        jPanel3.add(jLabel_Formato_OpeCos);

        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("FueCos");
        jPanel3.add(jLabel30);

        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Fuel Importation Cost");
        jPanel3.add(jLabel31);

        jLabel_Formato_FueCos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Formato_FueCos.setText("TS");
        jPanel3.add(jLabel_Formato_FueCos);

        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("PolCos");
        jPanel3.add(jLabel33);

        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Policies Cost");
        jPanel3.add(jLabel34);

        jLabel_Formato_PolCos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Formato_PolCos.setText("N x TS");
        jPanel3.add(jLabel_Formato_PolCos);

        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("GHGEmi");
        jPanel3.add(jLabel36);

        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("GHG Emissions");
        jPanel3.add(jLabel37);

        jLabel_Formato_GHGEmi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Formato_GHGEmi.setText("N x TS");
        jPanel3.add(jLabel_Formato_GHGEmi);

        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("WatCon");
        jPanel3.add(jLabel39);

        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("Water Consumption");
        jPanel3.add(jLabel40);

        jLabel_Formato_WatCon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Formato_WatCon.setText("N x TS");
        jPanel3.add(jLabel_Formato_WatCon);

        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("WatWit");
        jPanel3.add(jLabel42);

        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText("Water Withdrawal");
        jPanel3.add(jLabel43);

        jLabel_Formato_WatWit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Formato_WatWit.setText("N x TS");
        jPanel3.add(jLabel_Formato_WatWit);

        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("InvCapEmp");
        jPanel3.add(jLabel45);

        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setText("Investment Employment");
        jPanel3.add(jLabel46);

        jLabel_Formato_InvCapEmp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Formato_InvCapEmp.setText("N x TS");
        jPanel3.add(jLabel_Formato_InvCapEmp);

        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel48.setText("ManCapEmp");
        jPanel3.add(jLabel48);

        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel49.setText("Manufacture Employment");
        jPanel3.add(jLabel49);

        jLabel_Formato_ManCapEmp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Formato_ManCapEmp.setText("N x TS");
        jPanel3.add(jLabel_Formato_ManCapEmp);

        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel51.setText("OpeCapEmp");
        jPanel3.add(jLabel51);

        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel52.setText("Operation Employment");
        jPanel3.add(jLabel52);

        jLabel_Formato_OpeCapEmp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Formato_OpeCapEmp.setText("N x TS");
        jPanel3.add(jLabel_Formato_OpeCapEmp);

        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel54.setText("FueCapEmp");
        jPanel3.add(jLabel54);

        jLabel55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel55.setText("Fuel Employment");
        jPanel3.add(jLabel55);

        jLabel_Formato_FueCapEmp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Formato_FueCapEmp.setText("N x TS");
        jPanel3.add(jLabel_Formato_FueCapEmp);

        jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel57.setText("RetCapEmp");
        jPanel3.add(jLabel57);

        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel58.setText("Retirement Employment");
        jPanel3.add(jLabel58);

        jLabel_Formato_RetCapEmp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Formato_RetCapEmp.setText("N x TS");
        jPanel3.add(jLabel_Formato_RetCapEmp);

        jLabel60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel60.setText("EneMarPri");
        jPanel3.add(jLabel60);

        jLabel61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel61.setText("Energy Market Price");
        jPanel3.add(jLabel61);

        jLabel_Formato_EneMarPri.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Formato_EneMarPri.setText("N x TS");
        jPanel3.add(jLabel_Formato_EneMarPri);

        jButton_Continue.setText("Continue");
        jButton_Continue.setEnabled(false);
        jButton_Continue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ContinueActionPerformed(evt);
            }
        });

        jButton_ShowMap.setText("Show loaded map");
        jButton_ShowMap.setEnabled(false);
        jButton_ShowMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ShowMapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_FilePath_MAP))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 78, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_ShowMap)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Continue)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jTextField_FilePath_MAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Continue)
                            .addComponent(jButton_ShowMap)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser JFC = new JFileChooser();
        //JFC.setMultiSelectionEnabled(true);
        JFC.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        AllOK = true;
        JFC.setFileFilter(new FileNameExtensionFilter("TXT", "txt"));

        boolean B_M = false, B_SN = false, B_FN = false, B_FU = false, B_TC = false;
        String TypeMap = "";

        if (JFC.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            jTextArea1.setText("Nodes size:\t" + Nodes + "\n");
            FILE = JFC.getSelectedFile();
            jTextField_FilePath_MAP.setText(FILE.getAbsolutePath());
            if (FILE.isDirectory()) {
                File Files[] = FILE.listFiles();
                for (File F : Files) {
                    if (F.getName().toLowerCase().endsWith("_polygon.txt")) {
                        TypeMap = F.getName().substring(4, F.getName().indexOf("_"));
                        jLabel_CHECK_MAP.setIcon(new ImageIcon(getClass().getResource("/ICON/UNCHECK.png")));
                        jLabel_CHECK_Fuel.setIcon(new ImageIcon(getClass().getResource("/ICON/UNCHECK.png")));
                        jLabel_CHECK_FullName.setIcon(new ImageIcon(getClass().getResource("/ICON/UNCHECK.png")));
                        jLabel_CHECK_ShortName.setIcon(new ImageIcon(getClass().getResource("/ICON/UNCHECK.png")));
                        jLabel_CHECK_Tech.setIcon(new ImageIcon(getClass().getResource("/ICON/UNCHECK.png")));
                        jLabel_Name_MAP.setText("null");
                        jLabel_Name_Fuel.setText("null");
                        jLabel_Name_FullName.setText("null");
                        jLabel_Name_ShortName.setText("null");
                        jLabel_Name_Tech.setText("null");
                    }
                }

                for (File F : Files) {
                    if (!B_M && F.getName().toLowerCase().endsWith("_polygon.txt")) {
                        B_M = true;
                        if (Nodes != (getNumLines(F) - 2) / 2) {
                            jTextArea1.append("ERROR:\t" + "The file " + F.getName() + " don't have a correct matriz. " + "\tNo exception\n");
                            AllOK = false;
                        } else {
                            jLabel_CHECK_MAP.setIcon(new ImageIcon(getClass().getResource("/ICON/CHECK.png")));
                            jLabel_Name_MAP.setText(F.getName());
                            FileMap = F;
                        }
                    }
                    if (!B_SN && F.getName().toLowerCase().endsWith("_shortname.txt")
                            && TypeMap.equals(F.getName().substring(4, F.getName().indexOf("_")))) {
                        B_SN = true;
                        if (Nodes != getNumLines(F)) {
                            jTextArea1.append("ERROR:\t" + "The file " + F.getName() + " don't have a correct matriz. " + "\tNo exception\n");
                            AllOK = false;
                        } else {
                            jLabel_CHECK_ShortName.setIcon(new ImageIcon(getClass().getResource("/ICON/CHECK.png")));
                            jLabel_Name_ShortName.setText(F.getName());
                            FileShortName = F;
                        }
                    }
                    if (!B_FN && F.getName().toLowerCase().endsWith("_fullname.txt")
                            && TypeMap.equals(F.getName().substring(4, F.getName().indexOf("_")))) {
                        B_FN = true;
                        if (Nodes != getNumLines(F)) {
                            jTextArea1.append("ERROR:\t" + "The file " + F.getName() + " don't have a correct matriz. " + "\tNo exception\n");
                            AllOK = false;
                        } else {
                            jLabel_CHECK_FullName.setIcon(new ImageIcon(getClass().getResource("/ICON/CHECK.png")));
                            jLabel_Name_FullName.setText(F.getName());
                            FileFullName = F;
                        }
                    }
                    if (!B_TC && F.getName().toLowerCase().endsWith("_techname.txt")
                            && TypeMap.equals(F.getName().substring(4, F.getName().indexOf("_")))) {
                        B_TC = true;
                        if (Tech != getNumLines(F)) {
                            jTextArea1.append("ERROR:\t" + "The file " + F.getName() + " don't have a correct matriz. " + "\tNo exception\n");
                            AllOK = false;
                        } else {
                            jLabel_CHECK_Tech.setIcon(new ImageIcon(getClass().getResource("/ICON/CHECK.png")));
                            jLabel_Name_Tech.setText(F.getName());
                            FileTechName = F;
                        }
                    }
                    if (!B_FU && F.getName().toLowerCase().endsWith("_fuelname.txt")
                            && TypeMap.equals(F.getName().substring(4, F.getName().indexOf("_")))) {
                        B_FU = true;
                        if (Fuel != getNumLines(F)) {
                            jTextArea1.append("ERROR:\t" + "The file " + F.getName() + " don't have a correct matriz. " + "\tNo exception\n");
                            AllOK = false;
                        } else {
                            jLabel_CHECK_Fuel.setIcon(new ImageIcon(getClass().getResource("/ICON/CHECK.png")));
                            jLabel_Name_Fuel.setText(F.getName());
                            FileFuelName = F;
                        }
                    }
                }

            } else {
                System.out.println("NOPE");
                //jTextField_FilePath_MAP.setText(FILE.getAbsolutePath());
                //jTextArea1.setText("Nodes size:\t" + (L - 2) / 2);
            }

            if (!B_FN) {
                jTextArea1.append("ERROR:\t" + "The file _FullName.txt was not found\n");
                AllOK = false;
            }
            if (!B_FU) {
                jTextArea1.append("ERROR:\t" + "The file _FuelName.txt was not found\n");
                AllOK = false;
            }
            if (!B_SN) {
                jTextArea1.append("ERROR:\t" + "The file _ShortName.txt was not found\n");
                AllOK = false;
            }
            if (!B_TC) {
                jTextArea1.append("ERROR:\t" + "The file _TechName.txt was not found\n");
                AllOK = false;
            }

            jButton_Continue.setEnabled(AllOK);
            jButton_ShowMap.setEnabled(AllOK);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton_ContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ContinueActionPerformed
        new OpenDataToDisplay(FileTechName, FileFuelName, FileMap, FileFullName, FileShortName, Nodes, TS, Years, Tech).setVisible(true);
    }//GEN-LAST:event_jButton_ContinueActionPerformed

    private void jButton_ShowMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ShowMapActionPerformed
        Preview();
    }//GEN-LAST:event_jButton_ShowMapActionPerformed

    private void jButton_HelpMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_HelpMapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_HelpMapActionPerformed

    private void Preview() {
        JFrame JF = new JFrame("Preview");
        JF.add(new MAP(FileMap.getAbsolutePath(), FileShortName, FileFullName, Nodes, false));
        JF.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        JF.setSize(800, 600);
        JF.setLocationRelativeTo(null);
        JF.setVisible(true);
    }

    private int getNumLines(File F) {
        BufferedReader BR = null;
        int L = 0;
        try {
            BR = new BufferedReader(new FileReader(F));
            L = BR.lines().toArray().length;

        } catch (FileNotFoundException ex) {
            Logger.getLogger(OpenCountryData.class
                    .getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                BR.close();
            } catch (IOException ex) {
                Logger.getLogger(OpenCountryData.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        return L;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_Continue;
    private javax.swing.JButton jButton_FuelName;
    private javax.swing.JButton jButton_HelpFullName;
    private javax.swing.JButton jButton_HelpMap;
    private javax.swing.JButton jButton_HelpShortName;
    private javax.swing.JButton jButton_HelpTechName;
    private javax.swing.JButton jButton_ShowMap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_CHECK_Fuel;
    private javax.swing.JLabel jLabel_CHECK_FullName;
    private javax.swing.JLabel jLabel_CHECK_MAP;
    private javax.swing.JLabel jLabel_CHECK_ShortName;
    private javax.swing.JLabel jLabel_CHECK_Tech;
    private javax.swing.JLabel jLabel_Formato_Cap;
    private javax.swing.JLabel jLabel_Formato_Dem;
    private javax.swing.JLabel jLabel_Formato_EneMarPri;
    private javax.swing.JLabel jLabel_Formato_ExiCap;
    private javax.swing.JLabel jLabel_Formato_FueCapEmp;
    private javax.swing.JLabel jLabel_Formato_FueCos;
    private javax.swing.JLabel jLabel_Formato_GHGEmi;
    private javax.swing.JLabel jLabel_Formato_Gen;
    private javax.swing.JLabel jLabel_Formato_InvCapEmp;
    private javax.swing.JLabel jLabel_Formato_InvCos;
    private javax.swing.JLabel jLabel_Formato_ManCapEmp;
    private javax.swing.JLabel jLabel_Formato_ManCos;
    private javax.swing.JLabel jLabel_Formato_NewCap;
    private javax.swing.JLabel jLabel_Formato_OpeCapEmp;
    private javax.swing.JLabel jLabel_Formato_OpeCos;
    private javax.swing.JLabel jLabel_Formato_PolCos;
    private javax.swing.JLabel jLabel_Formato_RetCapEmp;
    private javax.swing.JLabel jLabel_Formato_WatCon;
    private javax.swing.JLabel jLabel_Formato_WatWit;
    private javax.swing.JLabel jLabel_Name_Fuel;
    private javax.swing.JLabel jLabel_Name_FullName;
    private javax.swing.JLabel jLabel_Name_MAP;
    private javax.swing.JLabel jLabel_Name_ShortName;
    private javax.swing.JLabel jLabel_Name_Tech;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField_FilePath_MAP;
    // End of variables declaration//GEN-END:variables
}
